name: OPA Compliance Check

on:
  push:
    paths:
      - 'iac/**'
      - 'policy/**'

jobs:
  opa-policy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.41.0/conftest_0.41.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.41.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run OPA policy checks
        run: |
          conftest test . --policy policy/
